server:
  port: 4445
spring:
  profiles:
    active: ${ACTIVE_PROFILE:development}

---
spring:
  config:
    activate:
      on-profile: development
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://abul.db.elephantsql.com:5432/zhcoxdjq?currentSchema=treinamento}
    username: ${DB_USER:zhcoxdjq}
    password: ${DB_PASSWORD:V-SeMyOLaSRC5CCVCTt05M2FJOzv91jS}
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      minimum-idle: 1
      maximum-pool-size: 3

---
spring:
  config:
    activate:
      on-profile: production